Emotion (#4)
* rename packages/tf files

* add converted tfjs (GraphModel)
- convert tensorflow saved mode to TFJS loadable model.

* add EmotionDetectionPage

* renames

* add packages/emotion

* add packages/emotion

* renames; update styles; add new components ...

* add ImgElement;
- need to fix: `TypeError: env().platform.isTypedArray is not a function`

* use tf.v.4.1 (instead of 4.2)
- fix: TypeError: env(...).platform.isTypedArray is not a function

* add tfvis, bar char, test pngs ...

* fix bar chart